### ISSUE TITLE
这是六代u的吗？

### ISSUE THREAD

**Issue by mokeeqian** [Xiaoshiguang520/ASUS_FL5900UQ_CLOVER#1]
fl5900u有两个版本，6代U和7代U

**Comment by Xiaoshiguang520** [comment]
对

**Comment by mokeeqian** [comment]
> 对

7500u的能用吗？

**Comment by ghost** [comment]
> > 对
> 
> 7500u的能用吗？

同问

**Comment by mokeeqian** [comment]
好像不行，BIOS要降级。。。
我放弃了












mokeeQian
mokeeqian@qq.com


---原始邮件---
发件人: "ouyangliqun"<notifications@github.com&gt;
发送时间: 2021年1月29日(周五) 中午11:45
收件人: "Xiaoshiguang520/ASUS_FL5900UQ_CLOVER"<ASUS_FL5900UQ_CLOVER@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Pony Qian"<mokeeqian@gmail.com&gt;;
主题: Re: [Xiaoshiguang520/ASUS_FL5900UQ_CLOVER] 这是六代u的吗？ (#1)




   
对
  
7500u的能用吗？
  
同问

**Comment by mokeeqian** [comment]
> > > 对
> > 
> > 
> > 7500u的能用吗？
> 
> 同问

不能直接用，我在stackoverflow上看到说要把bios降级到某个版本才行。。。
